### ISSUE TITLE
Some accounts are missing balance information

### ISSUE THREAD

**Issue by mbospiir** [lunarway/openbanking#13] opened 2021-11-09 07:02 UTC
Hi,
`/aisp-pisp/accounts` endpoint does not provide balance information for some accounts. Why is that?
You can take a look at the response we got at `Mon, 08 Nov 2021 13:49:29 GMT`.

**Comment by dentych** [comment] 2021-11-15 09:33
@mbospiir Are you trying in Sandbox or Production?

**Comment by mbospiir** [comment] 2021-11-15 09:57
@dentych in production

**Comment by dentych** [comment] 2021-11-15 14:46
@mbospiir Is it possible you can try another request? The problem isn't fixed, but I made some changes to help me locate the problem. Thank you in advance 😄

**Comment by mbospiir** [comment] 2021-11-16 09:27
@dentych I asked the user to try again and we actually got the balances for the account.
Wierd, as when the issue occured last week, we tried several times and it was reproducable.

**Comment by dentych** [comment] 2021-11-16 09:59
@mbospiir Oh. Alright! Well, good that you get the balances now.

I'll close this issue, and if you see it again, please don't hesitate to open a new one and we'll have a look right away :)

**Closed by dentych** 2021-11-16 09:59 UTC
