### ISSUE TITLE
Country on SSN submission page

### ISSUE THREAD

**Issue by RafaCMendes** [lunarway/openbanking#68] opened 2024-02-23 09:48 UTC
Hello,

Is there a way to set the country of the SSN submission form before accessing the page?

Right now the default seems to be Denmark, and if we are dealing with users from Norway or Sweden we need to rely on them to notice that they need to change the country on the SSN submission page otherwise they will not be able to progress with the flow.
If there was a way for us to set the country beforehand this would greatly improve the user experience for Sweden and Norway.

Thank you in advance for the help.

**Comment by Crevil** [comment] 2024-02-23 10:10
You can use the `nationality` URL parameter. As an example setting `?nationality=se` will set the selection on the page to SE.

This looks like a duplicate of #39 just for bookkeeping.

I'm not sure this is documented anywhere though, so I think we will see to that.

**Comment by RafaCMendes** [comment] 2024-02-28 09:34
Hello @Crevil,

I've tried that but to not success. 
We start the authorisation flow with the `/auth` endpoint which then gets redirected to a `/connect` url. I've seen that the `/connect` url is able to use the `nationality` parameter however I believe we are not expected to use that one directly, correct? The `/auth` endpoint which we are expected to use does not seem to use the `nationality` parameter.

Can you help me understand what is wrong?

**Comment by AndersSoee** [comment] 2024-03-01 14:35
Hi @RafaCMendes 
We have just deployed an update, where we actually read the `nationality` parameter from the `/auth` endpoint.
Please let us know if that works for you.

**Comment by RafaCMendes** [comment] 2024-03-04 09:49
@AndersSoee Hi. Just tested and that works fine, thank you!

**Closed as completed** 2024-03-04 10:15 UTC
