### ISSUE TITLE
Error registering

### ISSUE THREAD

**Issue by milan0v** [lunarway/openbanking#48] opened 2023-07-17 12:18 UTC
curl -v -H "Content-Type: application/json" -X POST --data '{"redirectUris":["https://dev-api-symblepay.io/register"],"roles":["PSP_AI","PSP_PI"],"name":"dev-api-symblepay.io"}' --cacert C:/Users/User/Downloads/cacert.pem --cert qwac.crt --key qwac.key https://sandbox.openbanking.prod.lunar.app/tpp

Trying 52.209.139.169...
TCP_NODELAY set
Connected to sandbox.openbanking.prod.lunar.app (52.209.139.169) port 443 (#0)
ALPN, offering h2
ALPN, offering http/1.1
Enter PEM pass phrase:
Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@strength
successfully set certificate verify locations:
CAfile: C:/Users/User/Downloads/cacert.pem
CApath: none
TLSv1.2 (OUT), TLS handshake, Client hello (1):
TLSv1.2 (IN), TLS handshake, Server hello (2):
TLSv1.2 (IN), TLS handshake, Certificate (11):
TLSv1.2 (IN), TLS handshake, Server key exchange (12):
TLSv1.2 (IN), TLS handshake, Request CERT (13):
TLSv1.2 (IN), TLS handshake, Server finished (14):
TLSv1.2 (OUT), TLS handshake, Certificate (11):
TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
TLSv1.2 (OUT), TLS handshake, CERT verify (15):
TLSv1.2 (OUT), TLS change cipher, Client hello (1):
TLSv1.2 (OUT), TLS handshake, Finished (20):
TLSv1.2 (IN), TLS handshake, Finished (20):
SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
ALPN, server accepted to use h2
Server certificate:
subject: CN=sandbox.openbanking.prod.lunar.app
start date: Jun 7 10:56:56 2023 GMT
expire date: Sep 5 10:56:55 2023 GMT
subjectAltName: host "sandbox.openbanking.prod.lunar.app" matched cert's "sandbox.openbanking.prod.lunar.app"
issuer: C=US; O=Let's Encrypt; CN=R3
SSL certificate verify ok.
Using HTTP2, server supports multi-use
Connection state changed (HTTP/2 confirmed)
Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
Using Stream ID: 1 (easy handle 0x256cf7d4110)
POST /tpp HTTP/2
Host: sandbox.openbanking.prod.lunar.app
User-Agent: curl/7.55.1
Accept: /
Content-Type: application/json
Content-Length: 104

Connection state changed (MAX_CONCURRENT_STREAMS updated)!
We are completely uploaded and fine
< HTTP/2 400
< date: Thu, 13 Jul 2023 11:27:23 GMT
< content-type: text/html
< content-length: 208
<
<title>400 The SSL certificate error</title>
400 Bad Request
The SSL certificate error
nginx * Connection #0 to host sandbox.openbanking.prod.lunar.app left intact

**Comment by hoeg** [comment] 2023-07-31 08:12
Hi @milan0v, would it be possible for you to share your certificate with us? this way we can easily rule out of the issue is in the cert or if we have a bug on our end :)

**Comment by milan0v** [comment] 2023-07-31 09:43
We prefer not to share it, are there any steps we might take in order to make sure?

**Comment by hoeg** [comment] 2023-08-01 07:05
We only need the public information of the certificate. We do not want your private key or anything like that! The public certificate is the only thing we need. There are multiple places this can break so letting me run it on our side will massively speed up the process :) If you could make it available somewhere we can get it and run our checks on it.

**Comment by milan0v** [comment] 2023-09-07 07:19
Hey @hoeg,
I sent the certificate long ago but I have no answer. I sent another email on Tuesday. Can you take a look? 
Thanks

**Comment by hoeg** [comment] 2023-10-23 07:17
Your certificate does not seem to be valid for PSD2 access production access. Please provide a valid QWAC certificate to get access.

**Comment by milan0v** [comment] 2023-10-25 09:30
Hi @hoeg,
this is a test certificate issued by Microsec that is a European validated eidas issuer. Why it's not valid?

**Comment by milan0v** [comment] 2023-11-13 12:01
@hoeg, can you collaborate on this?

**Comment by hoeg** [comment] 2023-11-29 11:23
The sandbox url is https://tpp.openbanking-sandbox.prod.lunar.tech, I can see we have an issue with the docs there. We require a valid QWAC certificate that is on the trusted list.

**Comment by milan0v** [comment] 2023-12-05 11:36
Hi @hoeg,
I tried with our production certificate and this is what I get:
![image](https://github.com/lunarway/openbanking/assets/75023012/480218da-d1c2-410d-8df0-a0a652aee45c)

**Comment by Crevil** [comment] 2023-12-05 13:01
Hi @milan0v .

Great level of detail you provide 👍
It looks as if you are not hitting the right path on that request.
Notice the [`/tpp`](https://developer.openbanking.prod.lunar.app/catalog/default/api/Registration) endpoint should be targeted as [documented](https://developer.openbanking.prod.lunar.app/docs/default/api/registration/register/).

We acknowledge that this is not super clear from the documentation and will release an update shortly making this more clear.

Can I get you to retry on the correct path?

**Comment by milan0v** [comment] 2023-12-05 13:06
Hi @Crevil,
same result: 
![image](https://github.com/lunarway/openbanking/assets/75023012/0948c4a1-5d0f-4a2d-96b6-3b631616f86c)

**Comment by Crevil** [comment] 2023-12-06 13:51
We can see the request but reject it due to an unknown signing authority.
It must contain the complete certificate chain specifically it must contain `leaf`, `intermediate`, and `root` in that order.

Can I get you to forward the contents of the provided certificate in argument `--certificate`? Either here or to me directly at bso@lunar.app. Either way, it is the public certificate so should not be a problem to share.

**Comment by milan0v** [comment] 2023-12-06 14:18
I have a pfx file and I'm trying to generate the .crt with openssl commands, do you know any tool that can help me with that ?

**Comment by Crevil** [comment] 2023-12-06 14:33
I'm afraid that is out of scope for the support I can provide you. Hopefully, you can find someone with knowledge of that specific format to assist you elsewhere.

Please circle back when you have the certificates ready for sharing and we will look in to it.

**Comment by milan0v** [comment] 2023-12-08 12:37
Hi @Crevil,
 I've sent you a new certificate, can you confirm that it has all needed info?

**Comment by Crevil** [comment] 2023-12-08 12:58
Thank you. We have reviewed your information. This file also only contains a single leaf certificate.

As a hint there should be several ```-----BEGIN CERTIFICATE-----``` lines in the PEM file. One for leaf, intermediate, and root. 🙏

**Comment by milan0v** [comment] 2023-12-12 12:32
Hi @Crevil, I've sent you a new certificate file, can you review it? Thanks

**Comment by Crevil** [comment] 2023-12-12 13:15
@milan0v I have not received anything yet. Can you confirm it was sent to bso@lunar.app?

**Comment by Crevil** [comment] 2023-12-12 14:33
Thank you for the provided details. From a brief look, this looks correct. Please attempt a new registration to see if it works as expected. Please post any details including timestamps for requests if the problem persists.

**Comment by milan0v** [comment] 2023-12-12 14:42
![image](https://github.com/lunarway/openbanking/assets/75023012/96a8b4c7-5227-48b1-992a-c87ab0e7e0a6)

**Comment by Crevil** [comment] 2023-12-13 12:30
Hi @milan0v,

We believe we are making progress.
We have made a change on our end that hopefully fixes your issue.
Can I get you to try again?

**Comment by milan0v** [comment] 2023-12-21 08:09
Hi @Crevil, nothing changed:
![image](https://github.com/lunarway/openbanking/assets/75023012/88780eb3-0d6f-404b-a56b-d468d1cc1c86)

**Comment by Crevil** [comment] 2023-12-22 13:04
Hi 👋 

We will do some more digging.
As we are in the holiday season we might not get back to you before the week of January 1st, 2024.

**Comment by Crevil** [comment] 2024-01-09 08:00
Hi @milan0v 

I hope you've had time to rest during the holiday season and happy new year 🎉 

We have investigated your issue further and come to the following conclusion.
It seems that when using the `wget` tool you need to specify the CA in a [separate argument](https://www.gnu.org/software/wget/manual/html_node/HTTPS-_0028SSL_002fTLS_0029-Options.html#HTTPS-_0028SSL_002fTLS_0029-Options) `--ca-certificate`.

```
‘--ca-certificate=file’
Use file as the file with the bundle of certificate authorities (“CA”) to verify the peers. The certificates must be in PEM format.

Without this option Wget looks for CA certificates at the system-specified locations, chosen at OpenSSL installation time.
```

You can test this out by pointing it to the same `all.pem` file you are using for `--certificate` although the more correct setup would be to split this into two files.

```
wget --certificate=all.pem --ca-certificate=all.pem ...
```

If you want to use minimal files you will ned to split up the `all.pem` file to have the leaf certificate in one file `leaf.pem` and the intermediate and root in another `inter-root.pem`.
You would then be able to run it like this.

```
wget --certificate=leave.pem --ca-certificate=inter-root.pem ...
```

Please let us know if the issue persists after applying above.

**Comment by milan0v** [comment] 2024-01-09 08:20
Hi @Crevil, Happy New Year!

![image](https://github.com/lunarway/openbanking/assets/75023012/a6ff9269-61b5-448d-8a93-5080bda226f1)

**Comment by Crevil** [comment] 2024-01-09 08:25
I can see that your arguments are using a full path in the `certificate` arg and a relative path in `ca-certificate`. Is that on purpose?

**Comment by milan0v** [comment] 2024-01-09 08:30
It doesn't matter:
![image](https://github.com/lunarway/openbanking/assets/75023012/52d1a451-4c3e-44a2-9ef9-a903c6c81fbf)

**Comment by Crevil** [comment] 2024-01-09 09:05
All right. Thanks. We are making progress. The 400 Bad Request means that the certificate chain is now valid and accepted. 🎉  Let me get back to you on what the error is. The 400 could mean several things so I'll get back to you.

**Comment by Crevil** [comment] 2024-01-09 09:09
Could you attempt to set the [`--debug` flag](https://www.gnu.org/software/wget/manual/html_node/Logging-and-Input-File-Options.html)? That will show you more about what might be wrong.

**Comment by milan0v** [comment] 2024-01-09 09:15
![image](https://github.com/lunarway/openbanking/assets/75023012/1fc53c6e-e22f-4b3b-8df1-a07a2621fc64)

**Comment by Crevil** [comment] 2024-01-09 09:59
It looks as if your shell is somehow not providing the payload correctly to `wget`.
We notice the debug information shows:

```
---request end---
[BODY data: '{redirectUris:[
```

That means your payload does literally contain `'` as the first character. It should look like this according to some internal tests we did with `wget`.

```
[BODY data: {"redirectUris":[
```

We don't know what shell environment you are using so this is somewhat hard for us to assist in. One idea is to avoid the `'` character and escape your JSON instead.

```
wget --post-data="{\"redirectUris\":...
```

**Comment by milan0v** [comment] 2024-01-09 10:41
![image](https://github.com/lunarway/openbanking/assets/75023012/4ab51532-eb59-4bee-a19b-54f0a8708ae5)

**Comment by Crevil** [comment] 2024-01-09 11:00
Hurray 🎉 You have now registered correctly in the sandbox environment.

It seems `wget` saves your credentials in a `tpp` file somewhere based on your screenshot. The response body of that request contains your client id and secret.

**Comment by milan0v** [comment] 2024-01-09 11:06
Woo-hoo, I found them, thanks a lot. 🥳

**Comment by Crevil** [comment] 2024-01-09 11:11
Great. 🤘 Happy hacking 🎉

**Closed** 2024-01-09 11:11 UTC
Labels: waiting for OP
